apiVersion: v1
kind: Pod
metadata:
  name: data-loader
  namespace: vorgabenui
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: alpine:3.20
      command: ["sh","-c","sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: django-data-pvc
