# Generated by Django 5.2.5 on 2025-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbschnittTyp',
            fields=[
                ('abschnitttyp', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Abschnitttypen',
            },
        ),
    ]
