apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-data-pvc
  namespace: vorgabenui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi

