apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroki
  namespace: vorgabenui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: web
          image: docker.io/yuzutech/kroki:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: svckroki
  namespace: vorgabenui
spec:
  selector:
    app: django
  ports:
    - port: 80
      targetPort: 80

