apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroki
  namespace: vorgabenui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kroki
  template:
    metadata:
      labels:
        app: kroki
    spec:
      containers:
        - name: kroki
          image: git.baumann.gr/adebaumann/kroki:0.026
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
        - name: mermaid
          image: git.baumann.gr/adebaumann/kroki-mermaid:0.026
          ports:
            - containerPort: 8002
        - name: bpmn
          image: git.baumann.gr/adebaumann/kroki-bpmn:0.026
          ports:
            - containerPort: 8003
        - name: excalidraw
          image: git.baumann.gr/adebaumann/kroki-excalidraw:0.026
          ports:
            - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: svckroki
  namespace: vorgabenui
spec:
  selector:
    app: kroki
  ports:
    - port: 8000
      targetPort: 8000