# Generated by Django 5.2.5 on 2025-09-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referenz',
            table=None,
        ),
        migrations.AlterModelTable(
            name='referenzerklaerung',
            table=None,
        ),
    ]
