# Generated by Django 5.2.5 on 2025-11-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0002_alter_referenz_table_alter_referenzerklaerung_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenzerklaerung',
            options={'verbose_name': 'Erklärung', 'verbose_name_plural': 'Erklärungen'},
        ),
    ]
