# Generated by Django 5.2.5 on 2025-10-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0005_vorgabe_relevanz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standard',
            new_name='Dokument',
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
    ]
