# Generated by Django 5.2.5 on 2025-10-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0006_rename_standard_dokument_alter_dokument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'verbose_name': 'Changelog-Eintrag', 'verbose_name_plural': 'Changelog'},
        ),
        migrations.AlterModelOptions(
            name='checklistenfrage',
            options={'verbose_name': 'Frage für Checkliste', 'verbose_name_plural': 'Fragen für Checkliste'},
        ),
        migrations.AlterModelOptions(
            name='dokumententyp',
            options={'verbose_name': 'Dokumententyp', 'verbose_name_plural': 'Dokumententypen'},
        ),
        migrations.AlterModelOptions(
            name='vorgabelangtext',
            options={'verbose_name': 'Langtext-Abschnitt', 'verbose_name_plural': 'Langtext'},
        ),
    ]
