# Generated by Django 5.2.5 on 2025-10-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0007_alter_changelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='aktiv',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
