# Generated by Django 5.2.5 on 2025-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0008_dokument_aktiv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vorgabe',
            options={'ordering': ['order'], 'verbose_name_plural': 'Vorgaben'},
        ),
        migrations.AddField(
            model_name='vorgabe',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
