# Generated by Django 5.2.5 on 2025-11-27 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0009_alter_vorgabe_options_vorgabe_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VorgabenTable',
            fields=[
            ],
            options={
                'verbose_name': 'Vorgabe (Tabellenansicht)',
                'verbose_name_plural': 'Vorgaben (Tabellenansicht)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dokumente.vorgabe',),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'Personen'},
        ),
        migrations.CreateModel(
            name='VorgabeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vorgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dokumente.vorgabe')),
            ],
            options={
                'verbose_name': 'Vorgabe-Kommentar',
                'verbose_name_plural': 'Vorgabe-Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
