# Generated by Django 5.2.5 on 2025-08-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abschnitte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stichwort',
            fields=[
                ('stichwort', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stichworte',
            },
        ),
        migrations.CreateModel(
            name='Stichworterklaerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.TextField(blank=True, null=True)),
                ('abschnitttyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abschnitte.abschnitttyp')),
                ('erklaerung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stichworte.stichwort')),
            ],
            options={
                'verbose_name': 'Erklärung',
            },
        ),
    ]
