# Generated by Django 5.2.5 on 2025-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stichworte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stichworterklaerung',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
