# Generated by Django 5.2.5 on 2025-11-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stichworte', '0002_stichworterklaerung_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stichworterklaerung',
            options={'verbose_name': 'Erklärung', 'verbose_name_plural': 'Erklärungen'},
        ),
    ]
