# Generated by Django 5.2.5 on 2025-08-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abschnitte', '0001_initial'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einleitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.TextField(blank=True, null=True)),
                ('abschnitttyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abschnitte.abschnitttyp')),
                ('einleitung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards.standard')),
            ],
            options={
                'verbose_name': 'Einleitungs-Abschnitt',
                'verbose_name_plural': 'Einleitung',
            },
        ),
    ]
