# Generated by Django 5.2.5 on 2025-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_einleitung'),
    ]

    operations = [
        migrations.AddField(
            model_name='einleitung',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geltungsbereich',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referenzerklaerung',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vorgabekurztext',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vorgabelangtext',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
