# Generated by Django 5.2.5 on 2025-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenzen', '0001_initial'),
        ('standards', '0003_einleitung_order_geltungsbereich_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenzerklaerung',
            name='erklaerung',
        ),
        migrations.RemoveField(
            model_name='referenzerklaerung',
            name='abschnitttyp',
        ),
        migrations.AlterField(
            model_name='vorgabe',
            name='referenzen',
            field=models.ManyToManyField(blank=True, to='referenzen.referenz'),
        ),
        migrations.DeleteModel(
            name='Referenz',
        ),
        migrations.DeleteModel(
            name='Referenzerklaerung',
        ),
    ]
