# Generated by Django 5.2.5 on 2025-09-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollen', '0001_initial'),
        ('standards', '0004_remove_referenzerklaerung_erklaerung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgabe',
            name='relevanz',
            field=models.ManyToManyField(blank=True, to='rollen.rolle'),
        ),
    ]
